
[[sshconnection]]
#unique name for the wiki
name = "host1"
#http or git url
ipaddr = "134.209.91.78"
# port for ssh connection
port = 22
# local port on our machine, where the server runs
localport = 3001
# remote port
remoteport = 443
# user
user = "root"
tcprouter_secret = ""


[[sshconnection]]
#unique name for the wiki
name = "host2"
#http or git url
ipaddr = "134.209.251.65"
# port for ssh connection
port = 22
# local port on our machine, where the server runs
localport = 3001
# remote port
remoteport = 443
# user
user = "root"
tcprouter_secret = ""

[[sshconnection]]
#unique name for the wiki
name = "host3"
#http or git url
ipaddr = "161.35.45.209"
# port for ssh connection
port = 22
# local port on our machine, where the server runs
localport = 3001
# remote port
remoteport = 443
# user
user = "root"
tcprouter_secret = ""


