#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"


[[wiki]]
name = "sdk"
title = "Grid Manual"
url = "github.com/threefoldfoundation/info_tfgridsdk"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"
groups = ["admin"]
auth = true

[[wiki]]
name = "wiki"
url = "https://github.com/threefoldfoundation/info_threefold"
title = "ThreeFold Wiki"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "production"


#data of simulator exports
[[data]]
name = "simexports"
title = "Simulator data repo"
url = "https://github.com/threefoldfoundation/simulator_export"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "html"
environment = "production"



# von sub blog
[[blog]]
name = "vonsubblog"
title = "Von Sub Blog"
#http or git url
url = "https://github.com/VonSub/blog"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"

# xmon blog
[[blog]]
name = "xmonblog"
title = "Xmon Blog"
#http or git url
url = "https://gitlab.com/xmonader/sample-blog-jsx"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "master"
#switch branch automatically if the name given above and its different on FS
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"
