# von sub blog
[[blog]]
name = "vonsubblog"
title = "Von Sub Blog"
#http or git url
url = "https://github.com/VonSub/blog"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"

# xmon blog
[[blog]]
name = "xmonblog"
title = "Xmon Blog"
#http or git url
url = "https://gitlab.com/xmonader/sample-blog-jsx"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "master"
#switch branch automatically if the name given above and its different on FS
branchswitch = true
#path in the repo where the info is, std "src"
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"
